//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Northwind
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NorthwindEntities : DbContext
    {
        public NorthwindEntities()
            : base("name=NorthwindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Shipper> Shippers { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<AdvisoryNote> AdvisoryNotes { get; set; }
        public virtual DbSet<AdvisorySociety> AdvisorySocieties { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<Student_Misc> Student_Misc { get; set; }
        public virtual DbSet<vw_Matri_Grad_Dates> vw_Matri_Grad_Dates { get; set; }
        public virtual DbSet<v_studentsAll> v_studentsAll { get; set; }
        public virtual DbSet<v_StudentsSOM> v_StudentsSOM { get; set; }
    }
}
