//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicPlan
    {
        public int id { get; set; }
        public string EMPLID { get; set; }
        public string ACAD_CAREER { get; set; }
        public int STDNT_CAR_NBR { get; set; }
        public System.DateTime EFFDT { get; set; }
        public int EFFSEQ { get; set; }
        public string ACAD_PLAN { get; set; }
        public System.DateTime DECLARE_DT { get; set; }
        public int PLAN_SEQUENCE { get; set; }
        public string REQ_TERM { get; set; }
    }
}
