//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicProgram
    {
        public int id { get; set; }
        public string EMPLID { get; set; }
        public string ACAD_CAREER { get; set; }
        public Nullable<int> STDNT_CAR_NBR { get; set; }
        public Nullable<System.DateTime> EFFDT { get; set; }
        public Nullable<int> EFFSEQ { get; set; }
        public string INSTITUTION { get; set; }
        public string ACAD_PROG { get; set; }
        public string PROG_STATUS { get; set; }
        public string PROG_ACTION { get; set; }
        public Nullable<System.DateTime> ACTION_DT { get; set; }
        public string PROG_REASON { get; set; }
        public string ADMIT_TERM { get; set; }
        public string EXP_GRAD_TERM { get; set; }
        public string REQ_TERM { get; set; }
        public string ACAD_LOAD_APPR { get; set; }
        public string CAMPUS { get; set; }
        public string COMPLETION_TERM { get; set; }
    }
}
