//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicPlanTbl
    {
        public int id { get; set; }
        public string INSTITUTION { get; set; }
        public string ACAD_PLAN { get; set; }
        public Nullable<System.DateTime> EFFDT { get; set; }
        public string EFF_STATUS { get; set; }
        public string DESCR { get; set; }
        public string DESCRSHORT { get; set; }
        public string ACAD_PLAN_TYPE { get; set; }
        public string ACAD_PROG { get; set; }
        public string PLN_REQTRM_DFLT { get; set; }
        public string DEGREE { get; set; }
        public string DIPLOMA_DESCR { get; set; }
        public string ACAD_CAREER { get; set; }
        public string DESCRLONG { get; set; }
    }
}
