//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvisoryGroup
    {
        public int id { get; set; }
        public string emaddr { get; set; }
        public string Advisor_Email { get; set; }
        public string release { get; set; }
    }
}
