//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMPCaseWesterUSNew
    {
        public int application_id { get; set; }
        public int app_year { get; set; }
        public bool IsCompleteApplication { get; set; }
        public bool IsInterviewedApplicant { get; set; }
        public bool IsOfferedApplicant { get; set; }
        public bool IsAcceptedApplicant { get; set; }
        public Nullable<bool> IsMatriculatedApplicant { get; set; }
        public string ProgramMatriculated { get; set; }
        public int IsInState { get; set; }
        public int IsOutState { get; set; }
        public int IsFemale { get; set; }
        public int IsURM { get; set; }
        public int IsDisadvantaged { get; set; }
        public int IsFirstGen { get; set; }
        public int IsMinority { get; set; }
        public int IsInternational { get; set; }
        public Nullable<long> amcas_id { get; set; }
        public string fullname { get; set; }
        public string perm_state_code { get; set; }
        public string school_state { get; set; }
        public string perm_country_code { get; set; }
        public string sex { get; set; }
        public string urm { get; set; }
        public Nullable<bool> self_reported_disadvantanged_ind { get; set; }
        public string self_reported_disadvantanged_yes_no { get; set; }
        public Nullable<bool> first_generation_ind { get; set; }
        public string first_generation_yes_no { get; set; }
        public string race_category_code { get; set; }
        public string race_category { get; set; }
        public string citizenship_country_code { get; set; }
        public string visa_type { get; set; }
        public string gender_identity_code { get; set; }
        public string gender_identity { get; set; }
    }
}
