//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_Class_Schedule
    {
        public int id { get; set; }
        public string Crse_ID { get; set; }
        public string course_type { get; set; }
        public string session_code { get; set; }
        public string ayear { get; set; }
        public string Day_Week { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
        public string Place { get; set; }
    }
}
