//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Mtg_Pat
    {
        public int id { get; set; }
        public string crse_id { get; set; }
        public Nullable<decimal> crse_offer_nbr { get; set; }
        public string strm { get; set; }
        public string session_code { get; set; }
        public string class_section { get; set; }
        public Nullable<decimal> class_mtg_nbr { get; set; }
        public string facility_id { get; set; }
        public Nullable<System.DateTime> meeting_time_start { get; set; }
        public Nullable<System.DateTime> meeting_time_end { get; set; }
        public string mon { get; set; }
        public string tues { get; set; }
        public string wed { get; set; }
        public string thurs { get; set; }
        public string fri { get; set; }
        public string sat { get; set; }
        public string sun { get; set; }
        public Nullable<System.DateTime> start_dt { get; set; }
        public Nullable<System.DateTime> end_dt { get; set; }
        public Nullable<decimal> crs_topic_id { get; set; }
        public string descr { get; set; }
        public string stnd_mtg_par { get; set; }
    }
}
