//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Notes
    {
        public string crse_id { get; set; }
        public decimal crse_offer_nbr { get; set; }
        public string strm { get; set; }
        public string session_code { get; set; }
        public string class_section { get; set; }
        public decimal class_notes_seq { get; set; }
        public string print_at { get; set; }
        public string class_note_nbr { get; set; }
        public string print_note_w_o_cls { get; set; }
        public string descrlong { get; set; }
    }
}
