//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_assoc
    {
        public int id { get; set; }
        public string crse_id { get; set; }
        public Nullable<decimal> crse_offer_nbr { get; set; }
        public string strm { get; set; }
        public string session_code { get; set; }
        public Nullable<decimal> associated_class { get; set; }
        public Nullable<decimal> units_minimum { get; set; }
        public Nullable<decimal> units_maximum { get; set; }
        public Nullable<decimal> units_acad_prog { get; set; }
        public Nullable<decimal> units_finaid_prog { get; set; }
        public string grading_basis { get; set; }
        public string grade_roster_print { get; set; }
        public string ssr_component { get; set; }
        public Nullable<decimal> billing_factor { get; set; }
        public Nullable<decimal> crse_contact_hrs { get; set; }
        public string rqrmnt_group { get; set; }
        public string use_catlg_rqs { get; set; }
        public string rqmnt_designtn { get; set; }
        public Nullable<decimal> crse_count { get; set; }
        public string instructor_edit { get; set; }
        public string use_blind_grading { get; set; }
        public string sel_group { get; set; }
        public string component_primary { get; set; }
        public string update_stdnt_enrl { get; set; }
    }
}
