//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_notes_Tbl
    {
        public string institution { get; set; }
        public string class_note_nbr { get; set; }
        public System.DateTime effdt { get; set; }
        public string eff_status { get; set; }
        public string descr { get; set; }
        public string descrlong { get; set; }
    }
}
