//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Tbl
    {
        public string crse_id { get; set; }
        public Nullable<decimal> crse_offer_nbr { get; set; }
        public string strm { get; set; }
        public string session_code { get; set; }
        public string class_section { get; set; }
        public string institution { get; set; }
        public string acad_group { get; set; }
        public string subject { get; set; }
        public string catalog_nbr { get; set; }
        public string acad_career { get; set; }
        public string descr { get; set; }
        public decimal class_nbr { get; set; }
        public string ssr_component { get; set; }
        public string enrl_stat { get; set; }
        public string class_stat { get; set; }
        public string class_type { get; set; }
        public Nullable<decimal> assoicated_class { get; set; }
        public string schedule_print { get; set; }
        public string consent { get; set; }
        public Nullable<decimal> enrl_cap { get; set; }
        public Nullable<decimal> min_enrl { get; set; }
        public Nullable<decimal> enrl_tot { get; set; }
        public Nullable<decimal> crs_topic_id { get; set; }
        public string print_topic { get; set; }
        public string acad_org { get; set; }
        public string campus { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> start_dt { get; set; }
        public Nullable<System.DateTime> end_dt { get; set; }
        public Nullable<System.DateTime> cancel_dt { get; set; }
        public string combined_section { get; set; }
        public string holiday_schedule { get; set; }
        public string fees_exist { get; set; }
        public string cncl_if_stud_enrod { get; set; }
        public string ssr_drop_consent { get; set; }
    }
}
