//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinical_Breaks
    {
        public int cal_id { get; set; }
        public string ayear { get; set; }
        public string CoreElec { get; set; }
        public string cal_type { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> wks { get; set; }
        public string cal_descr { get; set; }
    }
}
