//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicalCourse_Avail
    {
        public int elecid { get; set; }
        public Nullable<int> cdid { get; set; }
        public string session_id { get; set; }
        public Nullable<int> totavail { get; set; }
        public Nullable<int> totschedule { get; set; }
        public Nullable<System.DateTime> dateopen { get; set; }
        public Nullable<System.DateTime> dateclose { get; set; }
    }
}
