//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicalCourse_Request
    {
        public int reqid { get; set; }
        public string emaddr { get; set; }
        public Nullable<int> cdid { get; set; }
        public Nullable<int> session_id { get; set; }
        public string schdstatus { get; set; }
        public string studnote { get; set; }
        public Nullable<System.DateTime> studdate { get; set; }
        public string studuser { get; set; }
        public string coordnote { get; set; }
        public Nullable<System.DateTime> coorddate { get; set; }
        public string coorduser { get; set; }
        public string regnote { get; set; }
        public string reguser { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
