//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreClerk_Blocks
    {
        public int id { get; set; }
        public string ayear { get; set; }
        public string acadyear { get; set; }
        public int Block_Id { get; set; }
        public string Block_Code { get; set; }
        public string Block_Name { get; set; }
        public string Block_CID1 { get; set; }
        public string Block_Course1 { get; set; }
        public string Block_CID2 { get; set; }
        public string Block_Course2 { get; set; }
        public string Block_CID3 { get; set; }
        public string Block_Course3 { get; set; }
        public string Block_CID4 { get; set; }
        public string Block_Course4 { get; set; }
        public string Block_CID5 { get; set; }
        public string Block_Course5 { get; set; }
    }
}
