//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreClinical_Coordinators
    {
        public int id { get; set; }
        public string loc_code { get; set; }
        public int core_code { get; set; }
        public int rotation_code { get; set; }
        public string rotation { get; set; }
        public string coord_name { get; set; }
        public string coord_email { get; set; }
        public string coord_fax { get; set; }
        public string comments { get; set; }
    }
}
