//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreClinical_Sched_12
    {
        public Nullable<int> id { get; set; }
        public string emaddr { get; set; }
        public string ayear { get; set; }
        public string blk_schedule { get; set; }
        public string session_id1 { get; set; }
        public string session_id2 { get; set; }
        public Nullable<int> loc_id { get; set; }
    }
}
