//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreClinical_LocSchedule_Reason
    {
        public int id { get; set; }
        public string ayear { get; set; }
        public string emaddr { get; set; }
        public int block_id { get; set; }
        public string session_id { get; set; }
        public Nullable<int> loc_id { get; set; }
        public Nullable<int> choice1 { get; set; }
        public Nullable<int> choice2 { get; set; }
        public Nullable<int> choice3 { get; set; }
        public Nullable<int> choice_id { get; set; }
        public string reason { get; set; }
        public Nullable<int> schdid { get; set; }
    }
}
