//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crse_Offer
    {
        public string crse_id { get; set; }
        public System.DateTime effdt { get; set; }
        public decimal crse_offer_nbr { get; set; }
        public string institution { get; set; }
        public string acad_group { get; set; }
        public string subject { get; set; }
        public string catalog_nbr { get; set; }
        public string course_approved { get; set; }
        public string campus { get; set; }
        public string schedule_print { get; set; }
        public string catalog_print { get; set; }
        public string sched_print_instr { get; set; }
        public string acad_org { get; set; }
        public string acad_career { get; set; }
        public string split_owner { get; set; }
        public string sched_term_roll { get; set; }
        public string rqrmnt_group { get; set; }
        public string cip_code { get; set; }
        public string schedule_course { get; set; }
        public string dyn_class_data { get; set; }
        public string ssr_crse_typoff_cd { get; set; }
    }
}
