//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class crse_Catalog
    {
        public string Crse_ID { get; set; }
        public System.DateTime Effdt { get; set; }
        public string Eff_Status { get; set; }
        public string Descr { get; set; }
        public string Equiv_Crse_ID { get; set; }
        public string consent { get; set; }
        public string Allow_Multi_Enroll { get; set; }
        public Nullable<decimal> Units_Minimum { get; set; }
        public Nullable<decimal> Units_Maximum { get; set; }
        public Nullable<decimal> Units_Acad_Prog { get; set; }
        public string Crse_Repeatable { get; set; }
        public Nullable<decimal> Units_Repeat_Limit { get; set; }
        public Nullable<decimal> Crse_Repeat_Limit { get; set; }
        public string Grading_Basis { get; set; }
        public string Grade_Roster_Print { get; set; }
        public string Ssr_Component { get; set; }
        public string Course_Title_Long { get; set; }
        public string Lst_Mult_Trm_Crs { get; set; }
        public Nullable<decimal> Crse_Contact_Hrs { get; set; }
        public string Rqmnt_Designtn { get; set; }
        public Nullable<decimal> Crse_Count { get; set; }
        public string Component_Primary { get; set; }
        public string Ssr_Drop_Consent { get; set; }
        public string Descrlong { get; set; }
    }
}
