//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crse_Topics
    {
        public string crse_id { get; set; }
        public System.DateTime effdt { get; set; }
        public decimal crs_topic_id { get; set; }
        public string descr { get; set; }
        public string descrshort { get; set; }
        public string crse_repeatable { get; set; }
        public Nullable<decimal> units_repeat_limit { get; set; }
        public Nullable<decimal> crse_repeat_limit { get; set; }
        public string descrformal { get; set; }
        public Nullable<decimal> crs_topic_link { get; set; }
    }
}
