//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crse_Attr_Value
    {
        public string crse_attr { get; set; }
        public System.DateTime effdt { get; set; }
        public string crse_attr_value1 { get; set; }
        public string descr { get; set; }
        public string descrnormal { get; set; }
        public string catalog_print { get; set; }
        public string schedule_print { get; set; }
    }
}
