//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crse_Attributes
    {
        public string crse_id { get; set; }
        public System.DateTime effdt { get; set; }
        public string crse_attr { get; set; }
        public string crse_attr_value { get; set; }
    }
}
