//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class elec_StudRequest
    {
        public int reqid { get; set; }
        public Nullable<int> seqid { get; set; }
        public string emaddr { get; set; }
        public string ayear { get; set; }
        public string crse_id { get; set; }
        public string session_id { get; set; }
        public string reqtype { get; set; }
        public string studnote { get; set; }
        public Nullable<System.DateTime> studdate { get; set; }
        public string userid { get; set; }
        public Nullable<int> refreqid { get; set; }
    }
}
