//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class elec_Schedule
    {
        public int schedid { get; set; }
        public string crse_id { get; set; }
        public string ayear { get; set; }
        public string session_id { get; set; }
        public Nullable<int> maxseats { get; set; }
        public Nullable<System.DateTime> reqstartdate { get; set; }
        public Nullable<System.DateTime> reqenddate { get; set; }
        public Nullable<int> studstatusdays { get; set; }
        public Nullable<bool> canwithdraw { get; set; }
        public string userlogin { get; set; }
        public Nullable<System.DateTime> userdate { get; set; }
    }
}
