//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class elec_RefStatus
    {
        public int statusrefid { get; set; }
        public string reqtype { get; set; }
        public string statusgrp { get; set; }
        public string status { get; set; }
        public string statusdesc { get; set; }
    }
}
