//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emer_Contact
    {
        public int id { get; set; }
        public string Emplid { get; set; }
        public string Contact_Name { get; set; }
        public string Relationship { get; set; }
        public string phone_type { get; set; }
        public string phone { get; set; }
        public string extension { get; set; }
        public string xlatlongname { get; set; }
        public string main_phone { get; set; }
    }
}
