//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public string Emplid { get; set; }
        public string Acad_Career { get; set; }
        public string Strm { get; set; }
        public decimal Class_Nbr { get; set; }
        public string Crse_Career { get; set; }
        public string Session_Code { get; set; }
        public string Stdnt_Enrl_Status { get; set; }
        public string Enrl_Status_Reason { get; set; }
        public Nullable<decimal> Unt_Taken { get; set; }
        public Nullable<decimal> Unt_Earned { get; set; }
        public string Earn_Credit { get; set; }
        public string Grading_Basis_Enrl { get; set; }
        public string Crse_Grade_Off { get; set; }
    }
}
