//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradGrade
    {
        public int id { get; set; }
        public string EMPLID { get; set; }
        public string TEST_COMPONENT { get; set; }
        public string DESCR { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public Nullable<System.DateTime> TEST_DT { get; set; }
    }
}
