//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradCourseEnrolled
    {
        public int id { get; set; }
        public string EMPLID { get; set; }
        public string ACAD_CAREER { get; set; }
        public string STRM { get; set; }
        public decimal CLASS_NBR { get; set; }
        public string SUBJECT { get; set; }
        public string CATALOG_NBR { get; set; }
        public string DESCR { get; set; }
        public string CRSE_CAREER { get; set; }
        public string SESSION_CODE { get; set; }
        public string STDNT_ENRL_STATUS { get; set; }
        public string ENRL_STATUS_REASON { get; set; }
        public decimal UNT_TAKEN { get; set; }
        public decimal UNT_EARNED { get; set; }
        public string EARN_CREDIT { get; set; }
        public string GRADING_BASIS_ENRL { get; set; }
        public string CRSE_GRADE_OFF { get; set; }
        public Nullable<System.DateTime> GRADE_DT { get; set; }
    }
}
