//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradDegreeEnrolled
    {
        public int id { get; set; }
        public string EMPLID { get; set; }
        public string ACAD_CAREER { get; set; }
        public decimal STDNT_CAR_NBR { get; set; }
        public System.DateTime EFFDT { get; set; }
        public decimal EFFSEQ { get; set; }
        public string ACAD_PROG { get; set; }
        public string DESCR { get; set; }
        public string PROG_STATUS { get; set; }
        public string PROG_ACTION { get; set; }
        public string PROG_REASON { get; set; }
        public string ADMIT_TERM { get; set; }
        public System.DateTime TERM_BEGIN_DT { get; set; }
        public string EXP_GRAD_TERM { get; set; }
        public Nullable<System.DateTime> DEGR_CONFER_DT { get; set; }
        public string COMPLETION_TERM { get; set; }
        public string ADVISOR_ID { get; set; }
        public string NAME_PSFORMAT { get; set; }
        public string EMAIL_ADDR { get; set; }
        public string CAMPUS_ID { get; set; }
    }
}
