//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradDisabled
    {
        public int id { get; set; }
        public string EMPLID { get; set; }
        public string STDNT_GROUP { get; set; }
        public string DESCR { get; set; }
        public string EFF_STATUS { get; set; }
    }
}
