//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradProgramEnrolled
    {
        public int id { get; set; }
        public string EMPLID { get; set; }
        public string STRM { get; set; }
        public string BILLING_CAREER { get; set; }
        public string ACAD_PROG { get; set; }
        public string CW_ACAD_PROG_DESCR { get; set; }
        public string ACAD_PLAN { get; set; }
        public string CW_ACAD_PLAN_DESCR { get; set; }
        public string DEGREE { get; set; }
        public string ADMIT_TERM { get; set; }
        public string CW_ADMIT_TRM_DESCR { get; set; }
        public Nullable<System.DateTime> CW_MATRIC_DATE { get; set; }
        public string EXP_GRAD_TERM { get; set; }
        public Nullable<System.DateTime> DEGR_CONFER_DT { get; set; }
        public string LOCATION { get; set; }
        public string PROG_STATUS { get; set; }
    }
}
