//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradPriorCollege
    {
        public int id { get; set; }
        public string EMPLID { get; set; }
        public string CW_PRIOR_COLLEGE { get; set; }
        public Nullable<decimal> CW_PRIOR_COLL_GPA { get; set; }
    }
}
