//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradPersonal
    {
        public string EMPLID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string CW_PREF_FIRST_NAME { get; set; }
        public string CW_PREF_LAST_NAME { get; set; }
        public string CW_PREF_MID_NAME { get; set; }
        public string CAMPUS_ID { get; set; }
        public string SEX { get; set; }
        public string ETHNIC_GRP_CD { get; set; }
        public string CW_US_CITIZEN_CODE { get; set; }
        public string VISA_PERMIT_TYPE { get; set; }
        public string CW_CNTRY_OF_RSDNCY { get; set; }
        public string CW_EMAIL { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string CW_HOME_ADDRESS1 { get; set; }
        public string CW_HOME_ADDRESS2 { get; set; }
        public string CW_HOME_ADDRESS3 { get; set; }
        public string CW_HOME_CITY { get; set; }
        public string CW_HOME_STATE { get; set; }
        public string CW_HOME_POSTAL { get; set; }
        public string CW_HOME_CNTRY_DESC { get; set; }
        public string CW_CURR_ADDRESS1 { get; set; }
        public string CW_CURR_ADDRESS2 { get; set; }
        public string CW_CURR_ADDRESS3 { get; set; }
        public string CW_CURR_CITY { get; set; }
        public string CW_CURR_STATE { get; set; }
        public string CW_CURR_POSTAL { get; set; }
        public string CW_CURR_CNTRY_DESC { get; set; }
        public string CW_HOME_PHONE { get; set; }
        public string CW_CELL_PHONE { get; set; }
        public string CW_CC_GID_DESCR { get; set; }
        public string CW_CC_PRONOUN_DESCR { get; set; }
    }
}
