//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int somid { get; set; }
        public byte[] sid { get; set; }
        public string id { get; set; }
        public string ln { get; set; }
        public string fn { get; set; }
        public string mn { get; set; }
        public string suffix { get; set; }
        public string prevn { get; set; }
        public string sex { get; set; }
        public string isis_stat { get; set; }
        public Nullable<System.DateTime> mdt_yr1 { get; set; }
        public Nullable<System.DateTime> mdt_yr2 { get; set; }
        public Nullable<System.DateTime> mdt_yr3 { get; set; }
        public Nullable<System.DateTime> mdt_yr4 { get; set; }
        public Nullable<System.DateTime> mdt_yr5 { get; set; }
        public Nullable<System.DateTime> gdt { get; set; }
        public string gyr { get; set; }
        public string sd { get; set; }
        public Nullable<System.DateTime> bdt { get; set; }
        public string marst { get; set; }
        public string visa { get; set; }
        public string ccn { get; set; }
        public string stat { get; set; }
        public string confid { get; set; }
        public string ctryn { get; set; }
        public string octy { get; set; }
        public string comments { get; set; }
        public string pstreet { get; set; }
        public string pbldg { get; set; }
        public string pcity { get; set; }
        public string pstate { get; set; }
        public string pzip { get; set; }
        public string pzip_ext { get; set; }
        public string parea { get; set; }
        public string pexch { get; set; }
        public string pphone { get; set; }
        public string cstreet { get; set; }
        public string cbldg { get; set; }
        public string ccity { get; set; }
        public string cstate { get; set; }
        public string czip { get; set; }
        public string czip_ext { get; set; }
        public string carea { get; set; }
        public string cexch { get; set; }
        public string cphone { get; set; }
        public string emg_cont { get; set; }
        public string relation { get; set; }
        public string earea { get; set; }
        public string eexch { get; set; }
        public string ephone { get; set; }
        public string isis_ccd { get; set; }
        public string stat_code { get; set; }
        public string bstreet { get; set; }
        public string bbldg { get; set; }
        public string bcity { get; set; }
        public string bstate { get; set; }
        public string bzip { get; set; }
        public string bzip_ext { get; set; }
        public string barea { get; set; }
        public string bexch { get; set; }
        public string bphone { get; set; }
        public string desk_no { get; set; }
        public string fa { get; set; }
        public string statper { get; set; }
        public string statcur { get; set; }
        public string statbil { get; set; }
        public string res { get; set; }
        public string emaddr { get; set; }
        public string dcode { get; set; }
        public string pct { get; set; }
        public string repeat { get; set; }
        public string loa { get; set; }
        public string stpict { get; set; }
        public string vstreet { get; set; }
        public string vbldg { get; set; }
        public string vcity { get; set; }
        public string vstate { get; set; }
        public string vzip { get; set; }
        public string vzip_ext { get; set; }
        public string varea { get; set; }
        public string vexch { get; set; }
        public string vphone { get; set; }
        public string campuscode { get; set; }
        public string history_comments { get; set; }
        public string isisdesc { get; set; }
        public string ethnic { get; set; }
        public string reldesc { get; set; }
        public string state { get; set; }
        public string advname { get; set; }
        public string advemail { get; set; }
        public string county { get; set; }
    }
}
