//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class IApplyApplicantsArchieved
    {
        public int ID { get; set; }
        public Nullable<int> APPL_PERSON_ID { get; set; }
        public int APPL_YEAR { get; set; }
        public string ALT_ID { get; set; }
        public string AAMC_ID { get; set; }
        public string EMAIL { get; set; }
        public string TEMPPWD { get; set; }
        public string CaseID { get; set; }
        public string PIN { get; set; }
        public string STUDENT_ID { get; set; }
        public Nullable<bool> EMAIL_SENT { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public Nullable<System.DateTime> SENT_DATE { get; set; }
        public Nullable<System.DateTime> Remind_Date { get; set; }
        public Nullable<bool> UNIV_INVITE_SENT { get; set; }
        public Nullable<bool> CCLCM_INVITE_SENT { get; set; }
        public Nullable<bool> MSTP_INVITE_SENT { get; set; }
        public Nullable<System.DateTime> II_SENT_DATE { get; set; }
        public Nullable<bool> CONFIRMATION_SENT { get; set; }
        public Nullable<System.DateTime> CONF_SENT_DATE { get; set; }
        public Nullable<System.DateTime> SECOND_REMINDER { get; set; }
        public Nullable<System.DateTime> LETTERS_REMINDER { get; set; }
        public Nullable<System.DateTime> ACK_REMINDER { get; set; }
        public Nullable<System.DateTime> TECH_REMINDER { get; set; }
        public Nullable<System.DateTime> CLASS_INFO { get; set; }
        public Nullable<System.DateTime> INFO_REMINDER { get; set; }
        public Nullable<System.DateTime> RESOURCES { get; set; }
        public Nullable<System.DateTime> FIN_AID_INFO { get; set; }
        public Nullable<System.DateTime> CBC_DATE { get; set; }
        public byte[] SID { get; set; }
        public Nullable<System.DateTime> SIDDate { get; set; }
        public int PWVersion { get; set; }
        public string SecPwd { get; set; }
        public string race { get; set; }
        public string ethnicity { get; set; }
    }
}
