//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_Program
    {
        public int id { get; set; }
        public string Emplid { get; set; }
        public string Acad_Career { get; set; }
        public decimal Stdnt_Car_Nbr { get; set; }
        public Nullable<System.DateTime> Effdt { get; set; }
        public Nullable<decimal> Effseq { get; set; }
        public string Acad_Prog { get; set; }
        public string Descr { get; set; }
        public string Prog_Status { get; set; }
        public string Prog_Action { get; set; }
        public string Prog_Reason { get; set; }
        public string Admit_Term { get; set; }
        public Nullable<System.DateTime> Sess_Begin_Dt { get; set; }
        public string Exp_Grad_Term { get; set; }
        public Nullable<System.DateTime> Degr_Confer_Dt { get; set; }
        public string Completion_Term { get; set; }
        public string Stdnt_Attr_Value { get; set; }
        public string Advisor_ID { get; set; }
        public string CW_ATTR_VALUE_2 { get; set; }
        public string DESCRSHORT { get; set; }
    }
}
