//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program_Status
    {
        public int id { get; set; }
        public string prog_status { get; set; }
        public string Prog_Status_long { get; set; }
        public string Prog_Status_short { get; set; }
    }
}
