//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_CLASS_NOTES_Test
    {
        public string CRSE_ID { get; set; }
        public decimal CRSE_OFFER_NBR { get; set; }
        public string STRM { get; set; }
        public string SESSION_CODE { get; set; }
        public string CLASS_SECTION { get; set; }
        public decimal CLASS_NOTES_SEQ { get; set; }
        public string PRINT_AT { get; set; }
        public string CLASS_NOTE_NBR { get; set; }
        public string PRINT_NOTE_W_O_CLS { get; set; }
        public string DESCRLONG { get; set; }
    }
}
