//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistrarEntities1 : DbContext
    {
        public RegistrarEntities1()
            : base("name=RegistrarEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Acad_Org_Tbl> Acad_Org_Tbl { get; set; }
        public DbSet<AcademicPlan> AcademicPlans { get; set; }
        public DbSet<AcademicPlanTbl> AcademicPlanTbls { get; set; }
        public DbSet<AcademicProgram> AcademicPrograms { get; set; }
        public DbSet<AcademicSubPlan> AcademicSubPlans { get; set; }
        public DbSet<AcademicSubPlanTbl> AcademicSubPlanTbls { get; set; }
        public DbSet<AcademicYear> AcademicYears { get; set; }
        public DbSet<ADClassOfIgnore> ADClassOfIgnores { get; set; }
        public DbSet<ADClassOfInsert> ADClassOfInserts { get; set; }
        public DbSet<AdvancedCore_IDs> AdvancedCore_IDs { get; set; }
        public DbSet<AdvisoryGroup> AdvisoryGroups { get; set; }
        public DbSet<AdvisoryNote> AdvisoryNotes { get; set; }
        public DbSet<AdvisorySociety> AdvisorySocieties { get; set; }
        public DbSet<AMPCaseWesterUSNew> AMPCaseWesterUSNews { get; set; }
        public DbSet<BLSImport> BLSImports { get; set; }
        public DbSet<Campus_Tbl> Campus_Tbl { get; set; }
        public DbSet<Catalog_Class_Schedule> Catalog_Class_Schedule { get; set; }
        public DbSet<Catalog_Coordinators> Catalog_Coordinators { get; set; }
        public DbSet<Catalog_Course_Details> Catalog_Course_Details { get; set; }
        public DbSet<Catalog_Course_Type_Intro> Catalog_Course_Type_Intro { get; set; }
        public DbSet<Catalog_day_week> Catalog_day_week { get; set; }
        public DbSet<Catalog_Eval_Grade> Catalog_Eval_Grade { get; set; }
        public DbSet<Catalog_MCAT> Catalog_MCAT { get; set; }
        public DbSet<Class_assoc> Class_assoc { get; set; }
        public DbSet<Class_attribute> Class_attribute { get; set; }
        public DbSet<Class_Instr> Class_Instr { get; set; }
        public DbSet<Class_Mtg_Pat> Class_Mtg_Pat { get; set; }
        public DbSet<Class_Notes> Class_Notes { get; set; }
        public DbSet<Class_notes_Tbl> Class_notes_Tbl { get; set; }
        public DbSet<Class_Tbl> Class_Tbl { get; set; }
        public DbSet<Clinical_BlockMapping> Clinical_BlockMapping { get; set; }
        public DbSet<Clinical_Breaks> Clinical_Breaks { get; set; }
        public DbSet<Clinical_Calendar> Clinical_Calendar { get; set; }
        public DbSet<Clinical_Calendar_temp> Clinical_Calendar_temp { get; set; }
        public DbSet<ClinicalCourse_Avail> ClinicalCourse_Avail { get; set; }
        public DbSet<ClinicalCourse_Request> ClinicalCourse_Request { get; set; }
        public DbSet<ClinicalCourse_Status> ClinicalCourse_Status { get; set; }
        public DbSet<CoreBlock_List> CoreBlock_List { get; set; }
        public DbSet<CoreClerk_Blocks> CoreClerk_Blocks { get; set; }
        public DbSet<CoreClerk_Location> CoreClerk_Location { get; set; }
        public DbSet<CoreClinical_BlockLocSeats> CoreClinical_BlockLocSeats { get; set; }
        public DbSet<CoreClinical_Blocks> CoreClinical_Blocks { get; set; }
        public DbSet<CoreClinical_Coordinators> CoreClinical_Coordinators { get; set; }
        public DbSet<CoreClinical_LocRequest_Result> CoreClinical_LocRequest_Result { get; set; }
        public DbSet<CoreClinical_LocSchedule_Reason> CoreClinical_LocSchedule_Reason { get; set; }
        public DbSet<CoreClinical_Sched_12> CoreClinical_Sched_12 { get; set; }
        public DbSet<CoreClinical_Sched_34> CoreClinical_Sched_34 { get; set; }
        public DbSet<CoreClinical_Schedule> CoreClinical_Schedule { get; set; }
        public DbSet<CoreClinical_Schedule_Test> CoreClinical_Schedule_Test { get; set; }
        public DbSet<CoreClinical_Sessions> CoreClinical_Sessions { get; set; }
        public DbSet<CoreReqSchdType> CoreReqSchdTypes { get; set; }
        public DbSet<CoreReqSchedule> CoreReqSchedules { get; set; }
        public DbSet<Crse_Attr_Tbl> Crse_Attr_Tbl { get; set; }
        public DbSet<Crse_Attr_Value> Crse_Attr_Value { get; set; }
        public DbSet<Crse_Attributes> Crse_Attributes { get; set; }
        public DbSet<crse_Catalog> crse_Catalog { get; set; }
        public DbSet<Crse_Offer> Crse_Offer { get; set; }
        public DbSet<Crse_Topics> Crse_Topics { get; set; }
        public DbSet<elec_RefStatus> elec_RefStatus { get; set; }
        public DbSet<elec_Schedule> elec_Schedule { get; set; }
        public DbSet<elec_StudRequest> elec_StudRequest { get; set; }
        public DbSet<elec_StudRequestStatus> elec_StudRequestStatus { get; set; }
        public DbSet<Emer_Contact> Emer_Contact { get; set; }
        public DbSet<Enrollment> Enrollments { get; set; }
        public DbSet<Ethnicity> Ethnicities { get; set; }
        public DbSet<Faculty> Faculties { get; set; }
        public DbSet<GradCourseEnrolled> GradCourseEnrolleds { get; set; }
        public DbSet<GradDegreeEnrolled> GradDegreeEnrolleds { get; set; }
        public DbSet<GradDisabled> GradDisableds { get; set; }
        public DbSet<GradeCode> GradeCodes { get; set; }
        public DbSet<GradGrade> GradGrades { get; set; }
        public DbSet<GradPersonal> GradPersonals { get; set; }
        public DbSet<GradPriorCollege> GradPriorColleges { get; set; }
        public DbSet<GradProgramEnrolled> GradProgramEnrolleds { get; set; }
        public DbSet<History> Histories { get; set; }
        public DbSet<IApplyApplicantsArchieved> IApplyApplicantsArchieveds { get; set; }
        public DbSet<LCMEReason> LCMEReasons { get; set; }
        public DbSet<LeaveStatu> LeaveStatus { get; set; }
        public DbSet<Location_Tbl> Location_Tbl { get; set; }
        public DbSet<Matriculation_Dates> Matriculation_Dates { get; set; }
        public DbSet<Med_Program> Med_Program { get; set; }
        public DbSet<Personal> Personals { get; set; }
        public DbSet<Program_Status> Program_Status { get; set; }
        public DbSet<PS_Class_Notes_Trial> PS_Class_Notes_Trial { get; set; }
        public DbSet<Reason> Reasons { get; set; }
        public DbSet<ReqC_Blk_Available> ReqC_Blk_Available { get; set; }
        public DbSet<ReqC_Blk_Choice> ReqC_Blk_Choice { get; set; }
        public DbSet<ReqC_Blk_Choice_Result> ReqC_Blk_Choice_Result { get; set; }
        public DbSet<ReqC_Blk_Courses> ReqC_Blk_Courses { get; set; }
        public DbSet<ReqC_Blk_Request> ReqC_Blk_Request { get; set; }
        public DbSet<ReqC_Blk_Schedule> ReqC_Blk_Schedule { get; set; }
        public DbSet<ReqC_Loc_Choice> ReqC_Loc_Choice { get; set; }
        public DbSet<ReqC_Loc_Request> ReqC_Loc_Request { get; set; }
        public DbSet<ReqC_MJ_Block> ReqC_MJ_Block { get; set; }
        public DbSet<ReqC_MJ_Note> ReqC_MJ_Note { get; set; }
        public DbSet<ReqC_MJ_Questions> ReqC_MJ_Questions { get; set; }
        public DbSet<ReqC_MJ_Request> ReqC_MJ_Request { get; set; }
        public DbSet<RequestA> RequestAs { get; set; }
        public DbSet<RequestB> RequestBs { get; set; }
        public DbSet<RequestBArchieve> RequestBArchieves { get; set; }
        public DbSet<RequestC> RequestCs { get; set; }
        public DbSet<Scheyear> Scheyears { get; set; }
        public DbSet<sponsor_Address> sponsor_Address { get; set; }
        public DbSet<Stud_Ethnicity> Stud_Ethnicity { get; set; }
        public DbSet<Stud_Residency> Stud_Residency { get; set; }
        public DbSet<Stud_Term> Stud_Term { get; set; }
        public DbSet<Student_Billing> Student_Billing { get; set; }
        public DbSet<Student_Leaves> Student_Leaves { get; set; }
        public DbSet<Student_Misc> Student_Misc { get; set; }
        public DbSet<StudentAcademicSubPlan> StudentAcademicSubPlans { get; set; }
        public DbSet<StudentMatch> StudentMatches { get; set; }
        public DbSet<SUBJECT_Tbl> SUBJECT_Tbl { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TypeB_Breaks> TypeB_Breaks { get; set; }
        public DbSet<TypeB_Calendar> TypeB_Calendar { get; set; }
        public DbSet<Visa> Visas { get; set; }
        public DbSet<vw_Catalog_Section> vw_Catalog_Section { get; set; }
        public DbSet<vw_Catalog_Section_Other> vw_Catalog_Section_Other { get; set; }
        public DbSet<vw_Faculty_Class> vw_Faculty_Class { get; set; }
        public DbSet<vw_Matri_Grad_Dates> vw_Matri_Grad_Dates { get; set; }
        public DbSet<vw_Stud_Enrollment> vw_Stud_Enrollment { get; set; }
        public DbSet<vw_Stud_Enrollment_Other> vw_Stud_Enrollment_Other { get; set; }
        public DbSet<XLATITEM> XLATITEMs { get; set; }
        public DbSet<AdvisoryGroups12152020> AdvisoryGroups12152020 { get; set; }
        public DbSet<AspNet_SqlCacheTablesForChangeNotification> AspNet_SqlCacheTablesForChangeNotification { get; set; }
        public DbSet<Catalog_Coordinatorsbkup> Catalog_Coordinatorsbkup { get; set; }
        public DbSet<CoreClinical_Schedule_bkup10122017> CoreClinical_Schedule_bkup10122017 { get; set; }
        public DbSet<PS_CLASS_NOTES_Test> PS_CLASS_NOTES_Test { get; set; }
        public DbSet<ReqC_Blk_Schedule_Bkup10122017> ReqC_Blk_Schedule_Bkup10122017 { get; set; }
    }
}
