//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqC_Loc_Request
    {
        public int id { get; set; }
        public string ayear { get; set; }
        public string emaddr { get; set; }
        public string blk1_choice { get; set; }
        public string blk2_choice { get; set; }
        public string blk3_choice { get; set; }
        public string blk4_choice { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> req_date { get; set; }
    }
}
