//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqC_Blk_Request
    {
        public int id { get; set; }
        public string ayear { get; set; }
        public string emaddr { get; set; }
        public string blk_choice1 { get; set; }
        public string blk_choice2 { get; set; }
        public string blk_choice3 { get; set; }
        public string blk_choice4 { get; set; }
        public string blk_choice5 { get; set; }
        public Nullable<System.DateTime> req_date { get; set; }
        public string blk_comments { get; set; }
    }
}
