//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqC_Blk_Choice
    {
        public int id { get; set; }
        public string ayear { get; set; }
        public string groupid { get; set; }
        public int choice_id { get; set; }
        public string cwru_avail { get; set; }
        public string cclcm_avail { get; set; }
        public Nullable<int> max_seats { get; set; }
        public string cwru_block1 { get; set; }
        public string cwru_block2 { get; set; }
        public string cwru_block3 { get; set; }
        public string cwru_block4 { get; set; }
        public string cwru_block5 { get; set; }
        public string cwru_block6 { get; set; }
        public string cclcm_block1 { get; set; }
        public string cclcm_block2 { get; set; }
        public string cclcm_block3 { get; set; }
        public string cclcm_block4 { get; set; }
        public string cclcm_block5 { get; set; }
        public string cclcm_block6 { get; set; }
        public string cwru_comment1 { get; set; }
        public string cwru_comment2 { get; set; }
        public string cwru_comment3 { get; set; }
        public string cwru_comment4 { get; set; }
        public string cwru_comment5 { get; set; }
        public string cwru_comment6 { get; set; }
        public string cclcm_comment1 { get; set; }
        public string cclcm_comment2 { get; set; }
        public string cclcm_comment3 { get; set; }
        public string cclcm_comment4 { get; set; }
        public string cclcm_comment5 { get; set; }
        public string cclcm_comment6 { get; set; }
        public Nullable<int> totpergroup { get; set; }
    }
}
