//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqC_Blk_Schedule_Bkup10122017
    {
        public int id { get; set; }
        public string emaddr { get; set; }
        public string ayear { get; set; }
        public string blk_schedule { get; set; }
        public string block_seq1 { get; set; }
        public string block_seq2 { get; set; }
        public string block_seq3 { get; set; }
        public string block_seq4 { get; set; }
        public Nullable<System.DateTime> schedule_date { get; set; }
        public string userlogin { get; set; }
        public string reason_failed { get; set; }
        public Nullable<int> sched_choice_nbr { get; set; }
    }
}
