//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqC_MJ_Request
    {
        public int id { get; set; }
        public string emaddr { get; set; }
        public string ayear { get; set; }
        public string responses { get; set; }
        public string Blk_rank { get; set; }
        public string Loc_rank1 { get; set; }
        public string Loc_rank2 { get; set; }
        public string Loc_rank3 { get; set; }
        public string rs_comments { get; set; }
        public string blkloc_comments { get; set; }
        public Nullable<System.DateTime> req_date { get; set; }
    }
}
