//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestBArchieve
    {
        public int id { get; set; }
        public int seqid { get; set; }
        public string emaddr { get; set; }
        public string ayear { get; set; }
        public string subject { get; set; }
        public string catalog_nbr { get; set; }
        public System.DateTime start_dt { get; set; }
        public System.DateTime end_dt { get; set; }
        public string studnote { get; set; }
        public string regnote { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<System.DateTime> studdate { get; set; }
        public string rectype { get; set; }
        public string userid { get; set; }
    }
}
