//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestA
    {
        public string emaddr { get; set; }
        public string ayear { get; set; }
        public string period { get; set; }
        public string cour11 { get; set; }
        public string cour12 { get; set; }
        public string cour13 { get; set; }
        public string cour21 { get; set; }
        public string cour22 { get; set; }
        public string cour23 { get; set; }
        public Nullable<System.DateTime> submitdate { get; set; }
    }
}
