//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestC
    {
        public string emaddr { get; set; }
        public string ayear { get; set; }
        public string B1_Semester { get; set; }
        public string B1_Loc1 { get; set; }
        public string B1_Loc2 { get; set; }
        public string B1_Loc3 { get; set; }
        public string B2_Semester { get; set; }
        public string B2_Loc1 { get; set; }
        public string B2_Loc2 { get; set; }
        public string B2_Loc3 { get; set; }
        public string B3_Semester { get; set; }
        public string B3_Loc1 { get; set; }
        public string B3_Loc2 { get; set; }
        public string B3_Loc3 { get; set; }
        public string B4_Semester { get; set; }
        public string B4_Loc1 { get; set; }
        public string B4_Loc2 { get; set; }
        public string B4_Loc3 { get; set; }
    }
}
