//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAcademicSubPlan
    {
        public int id { get; set; }
        public string Emplid { get; set; }
        public string ACAD_PLAN { get; set; }
        public string ACD_SUBPLAN { get; set; }
        public Nullable<System.DateTime> DECLARE_DATE { get; set; }
        public string REQ_TERM { get; set; }
        public string planname { get; set; }
        public string subplanname { get; set; }
    }
}
