//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMatch
    {
        public int id { get; set; }
        public Nullable<double> Match_Year { get; set; }
        public string AAMC_ID { get; set; }
        public string NRMP_ID { get; set; }
        public string EmplID { get; set; }
        public string Network_ID { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public Nullable<System.DateTime> Grad_Date { get; set; }
        public string PG1_Pgm_Cd { get; set; }
        public string PG1_Inst_Name { get; set; }
        public string PG1_ACGME_Inst_Cd { get; set; }
        public string PG1_Pgm_Name { get; set; }
        public string PG1_City { get; set; }
        public string PG1_State_Cd { get; set; }
        public string PG1_Zipcode { get; set; }
        public string PG1_Pgm_Type_Cd { get; set; }
        public string PG1_Specialty_Desc { get; set; }
        public string PG1_ACGME_Cd { get; set; }
        public string PG1_ACGME_Osteopathic_Recognition { get; set; }
        public string PG2_Pgm_Cd { get; set; }
        public string PG2_Inst_Name { get; set; }
        public string PG2_ACGME_Inst_Cd { get; set; }
        public string PG2_Pgm_Name { get; set; }
        public string PG2_City { get; set; }
        public string PG2_State_Cd { get; set; }
        public string PG2_Zipcode { get; set; }
        public string PG2_Pgm_Type_Cd { get; set; }
        public string PG2_Specialty_Desc { get; set; }
        public string PG2_ACGME_Cd { get; set; }
        public string PG2_ACGME_Osteopathic_Recognition { get; set; }
    }
}
