//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Billing
    {
        public int id { get; set; }
        public string emplid { get; set; }
        public string ayear { get; set; }
        public string tuitionpercent { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
        public string userlogin { get; set; }
    }
}
