//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Leaves
    {
        public int id { get; set; }
        public string emplid { get; set; }
        public Nullable<System.DateTime> lsdate { get; set; }
        public Nullable<System.DateTime> ledate { get; set; }
        public Nullable<int> somreason { get; set; }
        public string lcmea { get; set; }
        public string lcmec { get; set; }
        public string academicyear { get; set; }
        public Nullable<System.DateTime> dateudpated { get; set; }
        public string userlogin { get; set; }
    }
}
