//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stud_Term
    {
        public int id { get; set; }
        public string Emplid { get; set; }
        public string Acad_Career { get; set; }
        public string Strm { get; set; }
        public string Withdraw_Code { get; set; }
        public Nullable<System.DateTime> Withdraw_Date { get; set; }
        public string Acad_Prog_Primary { get; set; }
        public string Academic_Load { get; set; }
        public string Acad_Level_BOT { get; set; }
        public string Acad_Level_EOT { get; set; }
        public string Elig_To_Enroll { get; set; }
        public Nullable<decimal> Cum_Resident_Terms { get; set; }
        public string Form_Of_Study { get; set; }
        public string Billing_Career { get; set; }
        public string Acad_Year { get; set; }
    }
}
