//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stud_Residency
    {
        public string emplid { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string county_cd { get; set; }
        public string county { get; set; }
    }
}
