//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Catalog_Section_Other
    {
        public int id { get; set; }
        public string Crse_ID { get; set; }
        public string Descr { get; set; }
        public Nullable<decimal> Units_Minimum { get; set; }
        public Nullable<decimal> Units_Maximum { get; set; }
        public string course_title { get; set; }
        public string subject { get; set; }
        public string catalog_nbr { get; set; }
        public string consent { get; set; }
        public string session_code { get; set; }
        public System.DateTime start_dt { get; set; }
        public System.DateTime end_dt { get; set; }
        public string acad_career { get; set; }
        public string ayear { get; set; }
        public string campus { get; set; }
        public string campus_detail { get; set; }
        public string location { get; set; }
        public string Descrlong { get; set; }
        public string Strm { get; set; }
        public Nullable<decimal> seats_sched { get; set; }
    }
}
