//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Faculty_Class
    {
        public int id { get; set; }
        public string Emplid { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Email_Addr { get; set; }
        public string Campus_Id { get; set; }
        public string Sex { get; set; }
        public string crse_id { get; set; }
        public string session_code { get; set; }
        public Nullable<System.DateTime> start_dt { get; set; }
        public Nullable<System.DateTime> end_dt { get; set; }
        public string ayear { get; set; }
        public string instr_role { get; set; }
        public decimal class_nbr { get; set; }
    }
}
