//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Stud_Enrollment
    {
        public int id { get; set; }
        public string Emplid { get; set; }
        public string Acad_Career { get; set; }
        public string Strm { get; set; }
        public decimal Class_nbr { get; set; }
        public string crse_id { get; set; }
        public string subject { get; set; }
        public string catalog_nbr { get; set; }
        public Nullable<System.DateTime> start_dt { get; set; }
        public Nullable<System.DateTime> end_dt { get; set; }
        public string session_code { get; set; }
        public string Acad_Prog_Primary { get; set; }
        public string Acad_Level_BOT { get; set; }
        public string Acad_Level_EOT { get; set; }
        public string ayear { get; set; }
        public string campus { get; set; }
        public string campus_detail { get; set; }
        public string Grading_Basis_Enrl { get; set; }
        public string Crse_Grade_Off { get; set; }
        public string course_type { get; set; }
        public string course_len { get; set; }
        public string location { get; set; }
        public string course_title { get; set; }
        public string Descrlong { get; set; }
    }
}
