//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Registrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class XLATITEM
    {
        public int id { get; set; }
        public string fieldname { get; set; }
        public string fieldvalue { get; set; }
        public Nullable<System.DateTime> effdt { get; set; }
        public string eff_status { get; set; }
        public string xlatlongname { get; set; }
        public string xlatshortname { get; set; }
    }
}
