//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Easel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentGradeCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentGradeCode()
        {
            this.AssessmentBlockComponentStudents = new HashSet<AssessmentBlockComponentStudent>();
            this.AssessmentGradeStudents = new HashSet<AssessmentGradeStudent>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string shortname { get; set; }
        public string detail { get; set; }
        public Nullable<bool> active { get; set; }
        public string userlogin { get; set; }
        public Nullable<System.DateTime> userdate { get; set; }
        public int grcode_old { get; set; }
        public string grname_old { get; set; }
        public string grnameabbr_old { get; set; }
        public string grnameshort_old { get; set; }
        public string details_old { get; set; }
        public string active_old { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentBlockComponentStudent> AssessmentBlockComponentStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentGradeStudent> AssessmentGradeStudents { get; set; }
    }
}
