//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Easel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentGradeStudent
    {
        public int id { get; set; }
        public Nullable<int> gyr { get; set; }
        public Nullable<int> somsectionblock_id { get; set; }
        public string emaddr { get; set; }
        public Nullable<int> assessmentgradecode_id { get; set; }
        public Nullable<int> assessmentnotmeetreasoncode_id { get; set; }
        public int attempt { get; set; }
        public Nullable<bool> release { get; set; }
        public string notes { get; set; }
        public string userlogin { get; set; }
        public Nullable<System.DateTime> userdate { get; set; }
        public Nullable<int> nmcode_old { get; set; }
        public string seyear_old { get; set; }
        public Nullable<int> bcode_old { get; set; }
        public string finalGrade_old { get; set; }
        public string release_old { get; set; }
    
        public virtual AssessmentGradeCode AssessmentGradeCode { get; set; }
    }
}
