//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Easel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentBlockComponent
    {
        public int id { get; set; }
        public Nullable<int> gyr { get; set; }
        public Nullable<int> somsectionblock_id { get; set; }
        public int assessmentblockcomponentdetail_id { get; set; }
        public string name { get; set; }
        public Nullable<bool> active { get; set; }
        public bool isRedirected { get; set; }
        public Nullable<int> sequence { get; set; }
        public string userlogin { get; set; }
        public Nullable<System.DateTime> userdate { get; set; }
        public string seyear_old { get; set; }
        public Nullable<int> bcode_old { get; set; }
        public string asscomp_old { get; set; }
        public string asssubcomp_old { get; set; }
        public string active_old { get; set; }
        public Nullable<int> seqnum_old { get; set; }
    
        public virtual AssessmentBlockComponentDetail AssessmentBlockComponentDetail { get; set; }
    }
}
