//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Data.Easel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssessmentBlockComponent> AssessmentBlockComponents { get; set; }
        public virtual DbSet<AssessmentBlockComponentDetail> AssessmentBlockComponentDetails { get; set; }
        public virtual DbSet<AssessmentBlockComponentStudent> AssessmentBlockComponentStudents { get; set; }
        public virtual DbSet<AssessmentGradeCode> AssessmentGradeCodes { get; set; }
        public virtual DbSet<AssessmentGradeStudent> AssessmentGradeStudents { get; set; }
    }
}
